[16-Feb-24 17:35:18 - INFO] - bot - Bot Running..!

Created by 
https://t.me/NKMDB
[16-Feb-24 17:35:18 - INFO] - bot -  

       
Bot Successfully Started at 2024-02-16 17:35:18.311140
[16-Feb-24 17:36:20 - ERROR] - pyrogram.dispatcher - 'set' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 252, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\handlers\message_handler.py", line 150, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "c:\Users\Hp\Music\FileShare\helper_func.py", line 25, in decorator
    return await message.reply_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\messages_and_media\message.py", line 1300, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\messages\send_message.py", line 169, in send_message
    r = await self.invoke(
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 402, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 320, in send
    message = self.msg_factory(data)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\internals\msg_factory.py", line 37, in __call__
    len(body)
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\tl_object.py", line 79, in __len__
    return len(self.write())
               ^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\functions\messages\send_message.py", line 171, in write
    b.write(self.reply_markup.write())
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\types\reply_inline_markup.py", line 71, in write
    b.write(Vector(self.rows))
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
                                   ^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\types\keyboard_button_row.py", line 71, in write
    b.write(Vector(self.buttons))
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
                                   ^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\types\keyboard_button_url.py", line 79, in write
    b.write(String(self.url))
            ^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\primitives\string.py", line 31, in __new__
    return super().__new__(cls, value.encode())
                                ^^^^^^^^^^^^
AttributeError: 'set' object has no attribute 'encode'
[16-Feb-24 17:37:46 - INFO] - root - Stop signal received (SIGINT). Exiting...
[16-Feb-24 17:37:46 - INFO] - bot - Bot stopped.
[16-Feb-24 17:37:57 - INFO] - bot - Bot Running..!

       
Bot Successfully Started at 2024-02-16 17:37:57.140964
[16-Feb-24 17:38:08 - ERROR] - pyrogram.dispatcher - 'list' object has no attribute 'write'
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 252, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\handlers\message_handler.py", line 150, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "c:\Users\Hp\Music\FileShare\helper_func.py", line 25, in decorator
    return await message.reply_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\messages_and_media\message.py", line 1300, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\messages\send_message.py", line 177, in send_message
    reply_markup=await reply_markup.write(self) if reply_markup else None,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\bots_and_keyboards\inline_keyboard_markup.py", line 63, in write
    buttons.append(await b.write(client))
                         ^^^^^^^
AttributeError: 'list' object has no attribute 'write'
[16-Feb-24 17:38:32 - INFO] - root - Stop signal received (SIGINT). Exiting...
[16-Feb-24 17:38:32 - INFO] - bot - Bot stopped.
[16-Feb-24 17:38:43 - INFO] - bot - Bot Running..!

       
Bot Successfully Started at 2024-02-16 17:38:43.271547
[16-Feb-24 17:38:47 - ERROR] - pyrogram.dispatcher - 'list' object has no attribute 'write'
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 252, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\handlers\message_handler.py", line 150, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "c:\Users\Hp\Music\FileShare\helper_func.py", line 25, in decorator
    return await message.reply_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\messages_and_media\message.py", line 1300, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\messages\send_message.py", line 177, in send_message
    reply_markup=await reply_markup.write(self) if reply_markup else None,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\bots_and_keyboards\inline_keyboard_markup.py", line 63, in write
    buttons.append(await b.write(client))
                         ^^^^^^^
AttributeError: 'list' object has no attribute 'write'
[16-Feb-24 17:39:04 - INFO] - root - Stop signal received (SIGINT). Exiting...
[16-Feb-24 17:39:04 - INFO] - bot - Bot stopped.
[16-Feb-24 17:39:15 - INFO] - bot - Bot Running..!

       
Bot Successfully Started at 2024-02-16 17:39:15.750336
[16-Feb-24 17:39:19 - ERROR] - pyrogram.dispatcher - 'set' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 252, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\handlers\message_handler.py", line 150, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "c:\Users\Hp\Music\FileShare\helper_func.py", line 25, in decorator
    return await message.reply_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\messages_and_media\message.py", line 1300, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\messages\send_message.py", line 169, in send_message
    r = await self.invoke(
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 402, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 320, in send
    message = self.msg_factory(data)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\internals\msg_factory.py", line 37, in __call__
    len(body)
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\tl_object.py", line 79, in __len__
    return len(self.write())
               ^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\functions\messages\send_message.py", line 171, in write
    b.write(self.reply_markup.write())
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\types\reply_inline_markup.py", line 71, in write
    b.write(Vector(self.rows))
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
                                   ^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\types\keyboard_button_row.py", line 71, in write
    b.write(Vector(self.buttons))
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
                                   ^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\types\keyboard_button_url.py", line 79, in write
    b.write(String(self.url))
            ^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\primitives\string.py", line 31, in __new__
    return super().__new__(cls, value.encode())
                                ^^^^^^^^^^^^
AttributeError: 'set' object has no attribute 'encode'
[16-Feb-24 17:40:49 - INFO] - root - Stop signal received (SIGINT). Exiting...
[16-Feb-24 17:40:49 - INFO] - bot - Bot stopped.
[16-Feb-24 17:41:00 - INFO] - bot - Bot Running..!

       
Bot Successfully Started at 2024-02-16 17:41:00.209658
[16-Feb-24 17:41:06 - ERROR] - pyrogram.dispatcher - 'list' object has no attribute 'write'
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 252, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\handlers\message_handler.py", line 150, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "c:\Users\Hp\Music\FileShare\helper_func.py", line 25, in decorator
    return await message.reply_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\messages_and_media\message.py", line 1300, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\messages\send_message.py", line 177, in send_message
    reply_markup=await reply_markup.write(self) if reply_markup else None,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\bots_and_keyboards\inline_keyboard_markup.py", line 63, in write
    buttons.append(await b.write(client))
                         ^^^^^^^
AttributeError: 'list' object has no attribute 'write'
[16-Feb-24 17:41:54 - INFO] - root - Stop signal received (SIGINT). Exiting...
[16-Feb-24 17:41:54 - INFO] - bot - Bot stopped.
[16-Feb-24 17:42:07 - INFO] - bot - Bot Running..!

       
Bot Successfully Started at 2024-02-16 17:42:07.280548
[16-Feb-24 17:42:15 - ERROR] - pyrogram.dispatcher - 'set' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 252, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\handlers\message_handler.py", line 150, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "c:\Users\Hp\Music\FileShare\helper_func.py", line 25, in decorator
    return await message.reply_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\messages_and_media\message.py", line 1300, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\messages\send_message.py", line 169, in send_message
    r = await self.invoke(
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 402, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 320, in send
    message = self.msg_factory(data)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\internals\msg_factory.py", line 37, in __call__
    len(body)
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\tl_object.py", line 79, in __len__
    return len(self.write())
               ^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\functions\messages\send_message.py", line 171, in write
    b.write(self.reply_markup.write())
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\types\reply_inline_markup.py", line 71, in write
    b.write(Vector(self.rows))
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
                                   ^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\types\keyboard_button_row.py", line 71, in write
    b.write(Vector(self.buttons))
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
                                   ^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\types\keyboard_button_url.py", line 79, in write
    b.write(String(self.url))
            ^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\raw\core\primitives\string.py", line 31, in __new__
    return super().__new__(cls, value.encode())
                                ^^^^^^^^^^^^
AttributeError: 'set' object has no attribute 'encode'
[16-Feb-24 17:44:15 - INFO] - root - Stop signal received (SIGINT). Exiting...
[16-Feb-24 17:44:15 - INFO] - bot - Bot stopped.
[16-Feb-24 17:44:25 - INFO] - bot - Bot Running..!

       
Bot Successfully Started at 2024-02-16 17:44:25.559170
[16-Feb-24 17:44:46 - ERROR] - pyrogram.dispatcher - 6040270724
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 252, in handler_worker
    await handler.callback(self.client, *args)
  File "c:\Users\Hp\Music\FileShare\plugins\start.py", line 20, in Join_requests_handler
    await add_fsub(message.chat.id, message.from_user.id)
  File "c:\Users\Hp\Music\FileShare\database\database.py", line 22, in add_fsub
    fsubs[channel_id].insert_one({'_id': user_id})
    ~~~~~^^^^^^^^^^^^
KeyError: 6040270724
[16-Feb-24 17:45:41 - INFO] - root - Stop signal received (SIGINT). Exiting...
[16-Feb-24 17:45:41 - INFO] - bot - Bot stopped.
[16-Feb-24 17:45:51 - INFO] - bot - Bot Running..!

       
Bot Successfully Started at 2024-02-16 17:45:51.940871
[16-Feb-24 17:46:10 - ERROR] - pyrogram.dispatcher - E11000 duplicate key error collection: mayava.-1002037461526 index: _id_ dup key: { _id: 6040270724 }, full error: {'index': 0, 'code': 11000, 'errmsg': 'E11000 duplicate key error collection: mayava.-1002037461526 index: _id_ dup key: { _id: 6040270724 }', 'keyPattern': {'_id': 1}, 'keyValue': {'_id': 6040270724}}
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 252, in handler_worker
    await handler.callback(self.client, *args)
  File "c:\Users\Hp\Music\FileShare\plugins\start.py", line 20, in Join_requests_handler
    await add_fsub(message.chat.id, message.from_user.id)
  File "c:\Users\Hp\Music\FileShare\database\database.py", line 22, in add_fsub
    fsubs[channel_id].insert_one({'_id': user_id})
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pymongo\collection.py", line 669, in insert_one
    self._insert_one(
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pymongo\collection.py", line 609, in _insert_one
    self.__database.client._retryable_write(acknowledged, _insert_command, session)
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pymongo\mongo_client.py", line 1523, in _retryable_write
    return self._retry_with_session(retryable, func, s, bulk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pymongo\mongo_client.py", line 1421, in _retry_with_session
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pymongo\_csot.py", line 107, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pymongo\mongo_client.py", line 1462, in _retry_internal
    ).run()
      ^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pymongo\mongo_client.py", line 2315, in run
    return self._read() if self._is_read else self._write()
                                              ^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pymongo\mongo_client.py", line 2422, in _write
    return self._func(self._session, conn, self._retryable)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pymongo\collection.py", line 607, in _insert_command
    _check_write_command_response(result)
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pymongo\helpers.py", line 266, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\pymongo\helpers.py", line 238, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: mayava.-1002037461526 index: _id_ dup key: { _id: 6040270724 }, full error: {'index': 0, 'code': 11000, 'errmsg': 'E11000 duplicate key error collection: mayava.-1002037461526 index: _id_ dup key: { _id: 6040270724 }', 'keyPattern': {'_id': 1}, 'keyValue': {'_id': 6040270724}}
[16-Feb-24 17:47:14 - INFO] - root - Stop signal received (SIGINT). Exiting...
[16-Feb-24 17:47:14 - INFO] - bot - Bot stopped.
[16-Feb-24 17:54:19 - INFO] - bot - Bot Running..!

       
Bot Successfully Started at 2024-02-16 17:54:19.794532
